# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "base"
  config.vm.network :hostonly, "33.33.33.10"

  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://api.opscode.com/organizations/nestorsalceda"
    chef.validation_key_path = "../chef-repo/.chef/nestorsalceda-validator.pem"
    chef.validation_client_name = "nestorsalceda-validator"

    chef.add_role "database"
    chef.add_role "viper"
  end
end
